kind: pipeline
type: kubernetes
name: PR

trigger:
  branch:
    - master
  event:
    include:
      - pull_request
steps:

- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
      
- name: discord-pr
  pull: always
  image: appleboy/drone-discord
  settings:
    avatar_url: https://png.pngitem.com/pimgs/s/88-881443_pink-line-art-head-white-cat-face-clipart.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_PR_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_PR_TOKEN  
  when:
    status: [success, failure]
---
kind: pipeline
type: kubernetes
name: Dev

trigger:
  branch:
    - master
  event:
    include:
      - push

steps:
- name: Build docker image & push to repository
  image: plugins/docker
  environment:
    REACT_APP_AUTH_CONFIG_CLIENT_SECRET:
      from_secret: DEV_AUTH_CLIENT_SECRET
    GITHUB_TOKEN:
      from_secret: GITHUB_PASSWORD
    REACT_APP_AUTH_CONFIG_CLIENT_ID:
      from_secret: DEV_AUTH_CLIENT_ID
  settings:
    registry: ghcr.io
    repo: ghcr.io/tipcat-net/tipcat-net-spa
    tags:
      - ${DRONE_COMMIT_SHA:0:7}-DEV
      - ${DRONE_COMMIT_BRANCH}
    force_tag: true
    use_cache: true
    username:
      from_secret: GITHUB_LOGIN
    password:
      from_secret: GITHUB_PASSWORD
    build_args_from_env:
      - GITHUB_TOKEN
      - REACT_APP_AUTH_CONFIG_CLIENT_SECRET
      - REACT_APP_AUTH_CONFIG_CLIENT_ID
      - REACT_APP_AUTH0_DOMAIN
      - REACT_APP_AUTH0_CLIENT_ID
- name: Deploy
  image: pelotech/drone-helm3
  settings:
    mode: upgrade
    chart: ./Helm
    release: spa
    values_files: ["Helm/values_dev.yaml"]
    namespace: dev
    skip_tls_verify: true
    wait_for_upgrade: true
    values: image.tag=${DRONE_COMMIT_SHA:0:7}-DEV
  environment:
    KUBE_API_SERVER:
      from_secret: KUBERNETES_DEV_API
    KUBE_TOKEN:
      from_secret: KUBERNETES_DEV_TOKEN

- name: discord
  pull: always
  image: appleboy/drone-discord
  settings:
    avatar_url: https://www.pngitem.com/pimgs/m/86-868269_drone-logo-png-transparent-drone-ci-logo-png.png
    message: "{{#success build.status}} ✅ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` on dev succeeded.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{else}} ❌ Build #{{build.number}}\n`{{ build.event }}` of `{{repo.name}}` on production failed.\n Commit by {{commit.author}} on `{{commit.branch}}`:\n``` {{commit.message}} ```\n{{ build.link }} {{/success}}"
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
  when:
    status: [success, failure]
