export const PaymentActionTypes = {
  GET_PAYMENT_START: 'GET_PAYMENT_START',
  GET_PAYMENT_FINISH: 'GET_PAYMENT_FINISH',
  GET_PAYMENT_ERROR: 'GET_PAYMENT_ERROR',
  
  CREATE_PAYMENT_START: 'CREATE_PAYMENT_START',
  CREATE_PAYMENT_FINISH: 'CREATE_PAYMENT_FINISH',
  CREATE_PAYMENT_ERROR: 'CREATE_PAYMENT_ERROR',
  
  UPDATE_PAYMENT_START: 'UPDATE_PAYMENT_START',
  UPDATE_PAYMENT_FINISH: 'UPDATE_PAYMENT_FINISH',
  UPDATE_PAYMENT_ERROR: 'UPDATE_PAYMENT_ERROR',
};
