export const PaymentActionTypes = {
  GET_PREPARE_PAYMENT_START: 'GET_PREPARE_PAYMENT_START',
  GET_PREPARE_PAYMENT_FINISH: 'GET_PREPARE_PAYMENT_FINISH',
  GET_PREPARE_PAYMENT_ERROR: 'GET_PREPARE_PAYMENT_ERROR',
  
  CREATE_PAYMENT_START: 'CREATE_PAYMENT_START',
  CREATE_PAYMENT_FINISH: 'CREATE_PAYMENT_FINISH',
  CREATE_PAYMENT_ERROR: 'CREATE_PAYMENT_ERROR',
};
