export const PaymentActionTypes = {
  GET_PAYMENT_START: 'GET_PAYMENT_START',
  GET_PAYMENT_FINISH: 'GET_PAYMENT_FINISH',
  GET_PAYMENT_ERROR: 'GET_PAYMENT_ERROR',

  CREATE_PAYMENT_INTENT_START: 'CREATE_PAYMENT_INTENT_START',
  CREATE_PAYMENT_INTENT_FINISH: 'CREATE_PAYMENT_INTENT_FINISH',
  CREATE_PAYMENT_INTENT_ERROR: 'CREATE_PAYMENT_INTENT_ERROR',

  CAPTURE_PAYMENT_START: 'CAPTURE_PAYMENT_START',
  CAPTURE_PAYMENT_FINISH: 'CAPTURE_PAYMENT_FINISH',
  CAPTURE_PAYMENT_ERROR: 'CAPTURE_PAYMENT_ERROR',

  UPDATE_PAYMENT: 'UPDATE_PAYMENT',

  UPDATE_PAYMENT_INTENT_START: 'UPDATE_PAYMENT_INTENT_START',
  UPDATE_PAYMENT_INTENT_FINISH: 'UPDATE_PAYMENT_INTENT_FINISH',
  UPDATE_PAYMENT_INTENT_ERROR: 'UPDATE_PAYMENT_INTENT_ERROR',
};
