export const TransactionActionTypes = {
  GET_TRANSACTIONS_START: 'GET_TRANSACTIONS_START',
  GET_TRANSACTIONS_FINISH: 'GET_TRANSACTIONS_FINISH',
  GET_TRANSACTIONS_ERROR: 'GET_TRANSACTIONS_ERROR',

  CHANGE_PARAMS_TRANSACTIONS: 'CHANGE_PARAMS_TRANSACTIONS',
};
