export const MemberActionTypes = {
  GET_MEMBER_START: 'GET_MEMBER_START',
  GET_MEMBER_ERROR: 'GET_MEMBER_ERROR',
  GET_MEMBER_FINISH: 'GET_MEMBER_FINISH',

  CREATE_MEMBER_START: 'CREATE_MEMBER_START',
  CREATE_MEMBER_ERROR: 'CREATE_MEMBER_ERROR',
  CREATE_MEMBER_FINISH: 'CREATE_MEMBER_FINISH',

  GET_MEMBER_BY_ID_START: 'GET_MEMBER_BY_ID_START',
  GET_MEMBER_BY_ID_ERROR: 'GET_MEMBER_BY_ID_ERROR',
  GET_MEMBER_BY_ID_FINISH: 'GET_MEMBER_BY_ID_FINISH',

  UPDATE_MEMBER_START: 'UPDATE_MEMBER_START',
  UPDATE_MEMBER_ERROR: 'UPDATE_MEMBER_ERROR',
  UPDATE_MEMBER_FINISH: 'UPDATE_MEMBER_FINISH',
};
