export const MemberActionTypes = {
  ADD_MEMBER_START: 'ADD_MEMBER_START',
  ADD_MEMBER_ERROR: 'ADD_MEMBER_ERROR',
  ADD_MEMBER_FINISH: 'ADD_MEMBER_FINISH',

  ADD_AVATAR_MEMBER_START: 'ADD_AVATAR_MEMBER_START',
  ADD_AVATAR_MEMBER_ERROR: 'ADD_AVATAR_MEMBER_ERROR',
  ADD_AVATAR_MEMBER_FINISH: 'ADD_AVATAR_MEMBER_FINISH',

  GET_MEMBER_START: 'GET_MEMBER_START',
  GET_MEMBER_ERROR: 'GET_MEMBER_ERROR',
  GET_MEMBER_FINISH: 'GET_MEMBER_FINISH',

  CREATE_MEMBER_START: 'CREATE_MEMBER_START',
  CREATE_MEMBER_ERROR: 'CREATE_MEMBER_ERROR',
  CREATE_MEMBER_FINISH: 'CREATE_MEMBER_FINISH',

  GET_MEMBER_BY_ID_START: 'GET_MEMBER_BY_ID_START',
  GET_MEMBER_BY_ID_ERROR: 'GET_MEMBER_BY_ID_ERROR',
  GET_MEMBER_BY_ID_FINISH: 'GET_MEMBER_BY_ID_FINISH',

  UPDATE_MEMBER_START: 'UPDATE_MEMBER_START',
  UPDATE_MEMBER_ERROR: 'UPDATE_MEMBER_ERROR',
  UPDATE_MEMBER_FINISH: 'UPDATE_MEMBER_FINISH',

  UPDATE_AVATAR_MEMBER_START: 'UPDATE_AVATAR_MEMBER_START',
  UPDATE_AVATAR_MEMBER_ERROR: 'UPDATE_AVATAR_MEMBER_ERROR',
  UPDATE_AVATAR_MEMBER_FINISH: 'UPDATE_AVATAR_MEMBER_FINISH',

  DELETE_MEMBER_START: 'DELETE_MEMBER_START',
  DELETE_MEMBER_ERROR: 'DELETE_MEMBER_ERROR',
  DELETE_MEMBER_FINISH: 'DELETE_MEMBER_FINISH',

  DEACTIVATE_MEMBER_START: 'DEACTIVATE_MEMBER_START',
  DEACTIVATE_MEMBER_ERROR: 'DEACTIVATE_MEMBER_ERROR',
  DEACTIVATE_MEMBER_FINISH: 'DEACTIVATE_MEMBER_FINISH',

  ACTIVATE_MEMBER_START: 'ACTIVATE_MEMBER_START',
  ACTIVATE_MEMBER_ERROR: 'ACTIVATE_MEMBER_ERROR',
  ACTIVATE_MEMBER_FINISH: 'ACTIVATE_MEMBER_FINISH',
};
