export const FacilityActionTypes = {
  GET_FACILITY_START: 'GET_FACILITY_START',
  GET_FACILITY_ERROR: 'GET_FACILITY_ERROR',
  GET_FACILITY_FINISH: 'GET_FACILITY_FINISH',

  GET_FACILITY_SLIM_START: 'GET_FACILITY_SLIM_START',
  GET_FACILITY_SLIM_ERROR: 'GET_FACILITY_SLIM_ERROR',
  GET_FACILITY_SLIM_FINISH: 'GET_FACILITY_SLIM_FINISH',
};
