export const FacilityActionTypes = {
  GET_FACILITIES: 'GET_FACILITIES',
  GET_FACILITIES_FINISH: 'GET_FACILITIES_FINISH',
  GET_FACILITIES_ERROR: 'GET_FACILITIES_ERROR',

  ADD_FACILITY_START: 'ADD_FACILITY_START',
  ADD_FACILITY_FINISH: 'ADD_FACILITY_FINISH',
  ADD_FACILITY_ERROR: 'ADD_FACILITY_ERROR',

  ADD_AVATAR_FACILITY_START: 'ADD_AVATAR_FACILITY_START',
  ADD_AVATAR_FACILITY_ERROR: 'ADD_AVATAR_FACILITY_ERROR',
  ADD_AVATAR_FACILITY_FINISH: 'ADD_AVATAR_FACILITY_FINISH',

  UPDATE_FACILITY_START: 'UPDATE_FACILITY_START',
  UPDATE_FACILITY_FINISH: 'UPDATE_FACILITY_FINISH',
  UPDATE_FACILITY_ERROR: 'UPDATE_FACILITY_ERROR',

  UPDATE_AVATAR_FACILITY_START: 'UPDATE_AVATAR_FACILITY_START',
  UPDATE_AVATAR_FACILITY_ERROR: 'UPDATE_AVATAR_FACILITY_ERROR',
  UPDATE_AVATAR_FACILITY_FINISH: 'UPDATE_AVATAR_FACILITY_FINISH',
};
