export const AccountActionTypes = {
  ADD_ACCOUNT_START: 'ADD_ACCOUNT_START',
  ADD_ACCOUNT_ERROR: 'ADD_ACCOUNT_ERROR',
  ADD_ACCOUNT_FINISH: 'ADD_ACCOUNT_FINISH',

  GET_ACCOUNT_START: 'GET_ACCOUNT_START',
  GET_ACCOUNT_ERROR: 'GET_ACCOUNT_ERROR',
  GET_ACCOUNT_FINISH: 'GET_ACCOUNT_FINISH',

  UPDATE_ACCOUNT_START: 'UPDATE_ACCOUNT_START',
  UPDATE_ACCOUNT_ERROR: 'UPDATE_ACCOUNT_ERROR',
  UPDATE_ACCOUNT_FINISH: 'UPDATE_ACCOUNT_FINISH',
};
