export const AppActionTypes = {
  // signIn
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_FINISH: 'SIGN_IN_FINISH',
  SIGN_IN_ERROR: 'SIGN_IN_ERROR',

  // signUp
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_FINISH: 'SIGN_UP_FINISH',
  SIGN_UP_ERROR: 'SIGN_UP_ERROR',

  SIGN_UP_MEMBER_START: 'SIGN_UP_MEMBER_START',
  SIGN_UP_MEMBER_FINISH: 'SIGN_UP_MEMBER_FINISH',
  SIGN_UP_MEMBER_ERROR: 'SIGN_UP_MEMBER_ERROR',

  SIGN_UP_ACCOUNT_START: 'SIGN_UP_ACCOUNT_START',
  SIGN_UP_ACCOUNT_FINISH: 'SIGN_UP_ACCOUNT_FINISH',
  SIGN_UP_ACCOUNT_ERROR: 'SIGN_UP_ACCOUNT_ERROR',
};
