name: CLEAR OLD BRANCHES

on:
  workflow_dispatch:
jobs:
  cleaning:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: clean
        uses: beatlabs/delete-old-branches-action@v0.0.10
        with:
          repo_token: ${{ secrets.GITTOKEN }}
          date: '12 month ago'
          dry_run: false
          delete_tags: false
          minimum_tags: 5
          exclude_open_pr_branches: true
          extra_protected_branch_regex: master.*|main|feature|^release.*|.*_p$
